### ISSUE TITLE
Some questions about NS3-for-authentication-schemes

### ISSUE THREAD

**Issue by suxinzhong** [soumyaxyz/NS3-for-authentication-schemes#1]
Hello
I had some problems emulating the code. I copied the PUF file to scratch directory, and then it failed to run (the specific problem is described in the attached picture). I hope you can have a look at it
Thank you very much.
[Picture description.docx](https://github.com/soumyaxyz/NS3-for-authentication-schemes/files/6607360/Picture.description.docx)

**Comment by soumyaxyz** [comment]
Updated 'iot_PUF.cc', added declaration for  maxPacketCount at line 45

This should solve the issue. For further issues look into the other files like' iot_MasterCopy.cc'.
